// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtu3oY49sezZNu_oIgNVh8uOLRyFaS-3I',
    appId: '1:105306415530:web:2909b849ca4890693b8bd3',
    messagingSenderId: '105306415530',
    projectId: 'hope-elearning-52e9b',
    authDomain: 'hope-elearning-52e9b.firebaseapp.com',
    storageBucket: 'hope-elearning-52e9b.firebasestorage.app',
    measurementId: 'G-5M0P8SBPDD',
    databaseURL: 'https://hope-elearning-52e9b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtu3oY49sezZNu_oIgNVh8uOLRyFaS-3I',
    appId: '1:105306415530:android:995daa86c4e966623b8bd3',
    messagingSenderId: '105306415530',
    projectId: 'hope-elearning-52e9b',
    storageBucket: 'hope-elearning-52e9b.firebasestorage.app',
    databaseURL: 'https://hope-elearning-52e9b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtu3oY49sezZNu_oIgNVh8uOLRyFaS-3I',
    appId: '1:105306415530:ios:995daa86c4e966623b8bd3',
    messagingSenderId: '105306415530',
    projectId: 'hope-elearning-52e9b',
    storageBucket: 'hope-elearning-52e9b.firebasestorage.app',
    iosBundleId: 'com.example.hopes',
    databaseURL: 'https://hope-elearning-52e9b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtu3oY49sezZNu_oIgNVh8uOLRyFaS-3I',
    appId: '1:105306415530:ios:995daa86c4e966623b8bd3',
    messagingSenderId: '105306415530',
    projectId: 'hope-elearning-52e9b',
    storageBucket: 'hope-elearning-52e9b.firebasestorage.app',
    iosBundleId: 'com.example.hopes',
    databaseURL: 'https://hope-elearning-52e9b-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}